### ISSUE TITLE
Double Folder Prepending

### ISSUE THREAD

**Issue by aperrien** [rajatomar788/pywebcopy#13]
Hey, I ran into an issue with folders pywebcopy's folder writes... 
I'm using Anaconda python 3, with pywebcopy 6.0.0.

My code looks like this:
```python
    kwargs = {'project_name': 'a_name'}

    save_webpage(
        url=URL,
        project_folder='p_folder',
        **kwargs
    )
```

URL is a valid URL, but when I run the program, I get this result:

```
C:\ProgramData\Anaconda3\python.exe H:/Python/PowerBee/URLDownloader.py
('t5_38jid', 'aipum7', 'Supreme Court lets Trump transgender troop restrictions take effect', 'https://www.reuters.com/article/us-usa-court-transgender/supreme-court-lets-trump-transgender-troop-restrictions-take-effect-idUSKCN1PG1RI')
Traceback (most recent call last):
  File "H:/Python/PowerBee/URLDownloader.py", line 38, in <module>
    **kwargs
  File "C:\ProgramData\Anaconda3\lib\site-packages\pywebcopy\api.py", line 56, in save_webpage
    config.setup_config(url, project_folder, project_name, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pywebcopy\configs.py", line 176, in setup_config
    self.setup_paths(project_folder, project_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pywebcopy\configs.py", line 138, in setup_paths
    f_stream = logging.FileHandler(lf, 'w')
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\ProgramData\Anaconda3\lib\logging\__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\Python\\PowerBee\\p_folder\\a_name\\p_folder\\a_name\\pywebcopy_log.log'

Process finished with exit code 1
```

It looks like the folder name and project name get appended to the path twice, somehow. The folder structure does seem to be created correctly by the pywebcopy, though. I'm not sure where in the library that file opening occurs. Could you take a look at it?

**Comment by rajatomar788** [comment]
Project folder needs to be absolute.

**Comment by aperrien** [comment]
Gotcha. Will mod code to that effect.

**Comment by michaelkonecny** [comment]
Is this just on Windows or also Linux?
Might be a good idea to note it in the readme ;)

**Comment by rajatomar788** [comment]
Its for all.
