### ISSUE TITLE
AttributeError: 'tuple' object attribute '__doc__' is read-only

### ISSUE THREAD

**Issue by snake-py** [rajatomar788/pywebcopy#132]
I am unsure why I get this:

```
DEBUG    - pywebcopy:56 - Added a stderr logging handler to logger: pywebcopy
DEBUG    - pywebcopy.configs:218 - {'debug': True, 'project_url': 'https://google.com', 'project_name': 'https_google.com', 'project_folder': '/home/fabio/Desktop/workdigital/other/demo/prokon_neu/https_google.com', 'threaded': False, 'thread_join_timeout': None, 'tree_type': 'HIERARCHY', 'overwrite': False, 'bypass_robots': True, 'http_cache': False, 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0 PyWebCopyBot/7.0.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.9'}, 'delay': None}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/fabio/Desktop/workdigital/other/demo/venv/lib/python3.11/site-packages/pywebcopy/__main__.py", line 59, in <module>
    save_webpage(
  File "/home/fabio/Desktop/workdigital/other/demo/venv/lib/python3.11/site-packages/pywebcopy/__init__.py", line 107, in save_page
    page = config.create_page()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/fabio/Desktop/workdigital/other/demo/venv/lib/python3.11/site-packages/pywebcopy/configs.py", line 241, in create_page
    from .core import WebPage
  File "/home/fabio/Desktop/workdigital/other/demo/venv/lib/python3.11/site-packages/pywebcopy/core.py", line 12, in <module>
    from .elements import HTMLResource
  File "/home/fabio/Desktop/workdigital/other/demo/venv/lib/python3.11/site-packages/pywebcopy/elements.py", line 150, in <module>
    class GenericResource(object):
  File "/home/fabio/Desktop/workdigital/other/demo/venv/lib/python3.11/site-packages/pywebcopy/elements.py", line 234, in GenericResource
    html_content_types.__doc__ = "Set of valid html mimetypes."
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Happens when running the following command:

```
python -m pywebcopy -p --url=https://google.com --location=./test
```

versions

```
beautifulsoup4==4.10.0
CacheControl==0.14.0
certifi==2024.8.30
charset-normalizer==3.3.2
idna==3.10
lxml==5.3.0
lxml_html_clean==0.2.2
msgpack==1.1.0
python-dotenv==0.19.2
pywebcopy==7.0.1
requests==2.32.3
six==1.16.0
soupsieve==2.6
urllib3==2.2.3
```

**Comment by rajatomar788** [comment]
Hey,
This is because the description attribute assignment of property is not
supported on some platforms. This is removed in the github repo code. You
can download the code from the repo.
It will work ok.

**Comment by rajatomar788** [comment]
Pypi version 7.1 has fixed this issue.
