### ISSUE TITLE
ValueError: path is on mount 'L:', start on mount 'C:'

### ISSUE THREAD

**Issue by KhairiAnuar** [rajatomar788/pywebcopy#14]
I am getting this error, Any idea why?

Code is just this on scrap.py
```
from pywebcopy import save_webpage
kwargs = {
    'project_folder': '/assets/saved_webPages',
    'project_name': 'localhost'
}
url = 'https://en.wikipedia.org/wiki/EndNote'
save_webpage(
    url=url,
    **kwargs
)

```
**Error Logs**
C:\xampp\htdocs\project\venv\Scripts\python.exe C:/xampp/htdocs/project/scrap.py
config     - INFO     - Got response <Response [200]> from https://en.wikipedia.org/robots.txt
config     - INFO     - Got response <Response [200]> from https://en.wikipedia.org/wiki/EndNote
webpage    - INFO     - Starting save_complete Action on url: ['https://en.wikipedia.org/wiki/EndNote']
parsers    - INFO     - Parsing tree with source: <<urllib3.response.HTTPResponse object at 0x03617850>> encoding <UTF-8> and parser <<lxml.etree.HTMLParser object at 0x035BEC30>>
Traceback (most recent call last):
  File "C:/xampp/htdocs/project/scrap.py", line 21, in <module>
    **kwargs
  File "C:\xampp\htdocs\project\venv\lib\site-packages\pywebcopy\api.py", line 88, in save_webpage
    wp.save_complete()
  File "C:\xampp\htdocs\project\venv\lib\site-packages\pywebcopy\webpage.py", line 275, in save_complete
    self.parse()  # call in the action
  File "C:\xampp\htdocs\project\venv\lib\site-packages\pywebcopy\parsers.py", line 192, in parse
    o = factory(elem, attr, url, pos)
  File "C:\xampp\htdocs\project\venv\lib\site-packages\pywebcopy\elements.py", line 456, in make_element
    rel_path = pathname2url(obj.relative_to(utx.file_path))
  File "C:\xampp\htdocs\project\venv\lib\site-packages\pywebcopy\urls.py", line 469, in relative_to
    rel_path = os.path.relpath(head, start)
  File "C:\Users\My Computer\AppData\Local\Programs\Python\Python37-32\lib\ntpath.py", line 562, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'L:', start on mount 'C:'

Process finished with exit code 1

**Comment by rajatomar788** [comment]
Project path must be an absolute address.

**Comment by KhairiAnuar** [comment]
Still getting same error with this 
` 'project_folder': 'C:/xampp/htdocs/project/assets/saved_webPages'`
but I am using a different tool now, thanks tho

**Comment by nxvinh222** [comment]
> Still getting same error with this
> ` 'project_folder': 'C:/xampp/htdocs/project/assets/saved_webPages'`
> but I am using a different tool now, thanks tho

I have same issue too, what tool are you using
