### ISSUE TITLE
FileNotFoundError while trying to do save_webpage

### ISSUE THREAD

**Issue by vinayshashank** [rajatomar788/pywebcopy#17]
Running below code snippet from the documentation is throwing a `FileNotFoundError`. Can you please check?

```from pywebcopy import save_webpage

url = 'https://pypi.org/project/pywebcopy/'

kwargs = {'project_name': 'some-fancy-name'}

save_webpage(
    url=url,
    project_folder='output/',
    **kwargs
)
```

Error Message:

`FileNotFoundError: [Errno 2] No such file or directory: '/Users/vinay/PycharmProjects/Web_Scraping/output/some-fancy-name/output/some-fancy-name/pywebcopy_log.log'`

Full traceback:

```Traceback (most recent call last):
  File "/Users/vinay/PycharmProjects/Web_Scraping/html_download.py", line 11, in <module>
    **kwargs
  File "/Users/vinay/anaconda3/envs/Web_Scraping/lib/python3.7/site-packages/pywebcopy/api.py", line 137, in save_website
    config.setup_config(url, project_folder, project_name, **kwargs)
  File "/Users/vinay/anaconda3/envs/Web_Scraping/lib/python3.7/site-packages/pywebcopy/configs.py", line 176, in setup_config
    self.setup_paths(project_folder, project_name)
  File "/Users/vinay/anaconda3/envs/Web_Scraping/lib/python3.7/site-packages/pywebcopy/configs.py", line 138, in setup_paths
    f_stream = logging.FileHandler(lf, 'w')
  File "/Users/vinay/anaconda3/envs/Web_Scraping/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Users/vinay/anaconda3/envs/Web_Scraping/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/vinay/PycharmProjects/Web_Scraping/output/some-fancy-name/output/some-fancy-name/pywebcopy_log.log'
```

Python Env: 3.7.3
OS: MacOS

**Comment by rajatomar788** [comment]
Use absolute address as project_folder instead of just "output/".
Let me know if this works for you.

**Comment by vinayshashank** [comment]
Working with an absolute path. Thanks!
