### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by gamel2018** [rajatomar788/pywebcopy#2]
**This is the program on Windows 10:**

from pywebcopy import save_webpage
save_webpage(
    project_url='https://www.google.com',
    project_folder='C:\\temp'
)

**This is the error:**

INFO - pywebcopy.parsers.html:125 - Using default Codec on raw_html!
Traceback (most recent call last):
  File "get_webcopy.py", line 12, in <module>
    project_folder='C:\\temp'
  File "C:\Program Files\Python37\lib\site-packages\pywebcopy\workers.py", line 60, in save_webpage
    WebPageParser(project_url, project_folder, project_name, encoding=encoding, HTML=html, **kwargs).save_complete()
  File "C:\Program Files\Python37\lib\site-packages\pywebcopy\parsers.py", line 594, in save_complete
    self.save_assets(reset_html=False)
  File "C:\Program Files\Python37\lib\site-packages\pywebcopy\parsers.py", line 578, in save_assets
    self._extractLinks()
  File "C:\Program Files\Python37\lib\site-packages\pywebcopy\parsers.py", line 510, in _extractLinks
    self.url_handler.handle(*i)
  File "C:\Program Files\Python37\lib\site-packages\pywebcopy\parsers.py", line 466, in url_handler
    self._url_handler = UrlHandler(self.url, self.url_obj.file_path)
  File "C:\Program Files\Python37\lib\site-packages\pywebcopy\parsers.py", line 457, in url_obj
    self._url_obj = Url(self.url)
  File "C:\Program Files\Python37\lib\site-packages\pywebcopy\urls.py", line 96, in __init__
    self.default_filename = self.hash() + (guess_extension(url) or '.download')
  File "C:\Program Files\Python37\lib\site-packages\pywebcopy\urls.py", line 108, in hash
    return str(int(hashlib.sha1(self.original_url).hexdigest(), 16) % (10 ** 8))
TypeError: Unicode-objects must be encoded before hashing

Any idea?

**Comment by rajatomar788** [comment]
Hey,
this issue happened due to the difference in the standard hashing libraries in python2 and python3.
So, i guess i will be releasing a patch `v4.0.1` to this library which should fix this issue on your python3 installation.
Thanks.

**Comment by rajatomar788** [comment]
Hey,
check the library now.
close this issue if you its solved.

**Comment by gamel2018** [comment]
Close
