### ISSUE TITLE
Python 2 UserDict

### ISSUE THREAD

**Issue by cbdwtv** [rajatomar788/pywebcopy#25]
For python 2 UserDict is in its own module UserDict.UserDict so an error occurs.
`
>>> import pywebcopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python-2.7.11_64\lib\site-packages\pywebcopy\__init__.py", line 49, in <module>
    from .configs import config, SESSION
  File "C:\Python-2.7.11_64\lib\site-packages\pywebcopy\configs.py", line 13, in <module>
    from collections import UserDict
ImportError: cannot import name UserDict
`

Just wanted to give a heads up in case you wanted to restrict the lib to py3 or update for py2 support.
Thanks!

**Comment by rajatomar788** [comment]
Okay I didn't knew that. It will be fixed in next update.

**Comment by rajatomar788** [comment]
fixed!
