### ISSUE TITLE
setup_config() got an unexpected keyword argument 'url'

### ISSUE THREAD

**Issue by kennym** [rajatomar788/pywebcopy#45]
Python version: 3.7.7

I'm using the same code as in the README, but I'm getting the following error when running it:

```
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    pywebcopy.config.setup_config(**kwargs)
TypeError: setup_config() got an unexpected keyword argument 'url'
```

This is the code:

```
import pywebcopy

# Rest of the code is as usual
kwargs = {
    'url': 'XXX',
    'project_folder': '/Users/kennymeyer/Projects/zyx',
    'project_name': 'zyx',
    'bypass_robots': True,
}
pywebcopy.config.setup_config(**kwargs)
pywebcopy.save_webpage(**kwargs)
```

What am I doing wrong?

**Comment by KuroiKuro** [comment]
Hi, I believe 'url' should be 'project_url'

**Comment by kennym** [comment]
When I do that, I get:

```
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    pywebcopy.save_webpage(**kwargs)
TypeError: save_webpage() missing 1 required positional argument: 'url'
```

**Comment by rajatomar788** [comment]
Try it out simply as documented.

``` python
from pywebcopy import save_webpage

save_webpage(
 'http://example-site.com/',
 project_folder='path/to/downloads',
 project_name='xyz', 
 bypass_robots=True
)

```

**Comment by dansaavedra** [comment]
> When I do that, I get:
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 15, in <module>
>     pywebcopy.save_webpage(**kwargs)
> TypeError: save_webpage() missing 1 required positional argument: 'url'
> ```

I was able to get it to work by using project_url for setup_config and then changing it back to url for save_webpage. Something like this:

```
import pywebcopy

# Rest of the code is as usual
kwargs = {
    'project_url': 'XXX',
    'project_folder': '/Users/kennymeyer/Projects/zyx',
    'project_name': 'zyx',
    'bypass_robots': True,
}

kwargs2 = {
    'url': 'XXX',
    'project_folder': '/Users/kennymeyer/Projects/zyx',
    'project_name': 'zyx',
    'bypass_robots': True,
}
pywebcopy.config.setup_config(**kwargs)
pywebcopy.save_webpage(**kwargs2)
```

**Comment by rajatomar788** [comment]
Ok cool.
I still don't understand, why you can't keep it simple? But your implementation is ok too, so no worries.

``` python
from pywebcopy import save_webpage

save_webpage(
 'http://example-site.com/',
 project_folder='path/to/downloads',
 project_name='xyz', 
 bypass_robots=True
)

```

**Comment by kennym** [comment]
@rajatomar788 I need to set custom cookies. How would I do that with your approach?

**Comment by rajatomar788** [comment]
If you need to set cookies then just import the SESSION variable from pywebcopy then configure it and continue as above. 

```python
import requests 
from pywebcopy import SESSION

cookie_obj = requests.cookies.create_cookie(domain='www.domain.com',name='COOKIE_NAME',value='the cookie works')
SESSION.cookies.set_cookie(cookie_obj)

# rest of the code as above... 

```
