### ISSUE TITLE
Cannot import name 'save_webpage' from 'pywebcopy'

### ISSUE THREAD

**Issue by slavakurilyak** [rajatomar788/pywebcopy#50]
I'm trying to replicate the basic example and running into an error.

```python
# pywebcopy.py
from pywebcopy import save_webpage

kwargs = {'project_name': 'some-fancy-name'}

save_webpage(
    url='http://example-site.com/index.html',
    project_folder='path/to/downloads',
    **kwargs
)
```

Running `$ python pywebcopy.py` gives me:

```shell
Traceback (most recent call last):
  File "pywebcopy.py", line 1, in <module>
    from pywebcopy import save_webpage
  File "/pywebcopy.py", line 1, in <module>
    from pywebcopy import save_webpage
ImportError: cannot import name 'save_webpage' from 'pywebcopy' (/pywebcopy.py)
```

I already installed pywebcopy using `$ pip install pywebcopy`

Please advise.

**Comment by rajatomar788** [comment]
You should rename your file from `pywebcopy.py` to something else. That's basic python ethics to **not** name your script after a library.

**Comment by slavakurilyak** [comment]
@rajatomar788 Thanks!
