### ISSUE TITLE
Documented command-line interface example fails

### ISSUE THREAD

**Issue by metaperl** [rajatomar788/pywebcopy#59]
The [command line interface](https://github.com/rajatomar788/pywebcopy#14-command-line-interface) claims that a command like this will work:

    python -m pywebcopy save_webpage https://www.maskupmanateecoalition.org

But instead the following error is thrown:

```
Traceback (most recent call last):
  File "C:\Users\thequ\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\thequ\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\thequ\anaconda3\lib\site-packages\pywebcopy\__main__.py", line 69, in <module>
    fire.Fire(Commands)
  File "C:\Users\thequ\anaconda3\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\thequ\anaconda3\lib\site-packages\fire\core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\thequ\anaconda3\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\thequ\anaconda3\lib\site-packages\pywebcopy\__main__.py", line 47, in save_webpage
    return swp(*args, **kwargs)
TypeError: save_webpage() missing 1 required positional argument: 'project_folder'
```

**Comment by rajatomar788** [comment]
It says right there in the error that you need to provide another argument which should be the destination folder.
