### ISSUE TITLE
Download only of package not possible

### ISSUE THREAD

**Issue by cmusik** [rajatomar788/pywebcopy#60]
To create a rpm package I need to download the tar.gz. But this failes as setup.py imports pywebcopy and so you need to have all dependencies installed on the build server:

```
buildhost :: /tmp » pip download --no-deps --no-binary=:all: pywebcopy
Collecting pywebcopy
  Downloading https://files.pythonhosted.org/packages/69/c1/e9b8429a34ccbfa446a0a019a21303d9496823b31a2c80f8946cb114c130/pywebcopy-6.3.0.tar.gz (52kB)
     |████████████████████████████████| 61kB 1.6MB/s 
  Saved ./pywebcopy-6.3.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-v2d6nmo5/pywebcopy/setup.py", line 14, in <module>
        import pywebcopy
      File "/tmp/pip-download-v2d6nmo5/pywebcopy/pywebcopy/__init__.py", line 50, in <module>
        from .parsers import Parser, MultiParser
      File "/tmp/pip-download-v2d6nmo5/pywebcopy/pywebcopy/parsers.py", line 19, in <module>
        from pyquery import PyQuery
    ModuleNotFoundError: No module named 'pyquery'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-download-v2d6nmo5/pywebcopy/
```

**Comment by rajatomar788** [comment]
@cmusik do a pr i will approve.
