### ISSUE TITLE
multiple bases have instance lay-out conflict

### ISSUE THREAD

**Issue by david0091** [rajatomar788/pywebcopy#95]
save_webpage(
      url="https://example.com",
      project_folder="C://project",
      project_name="my_site",
      bypass_robots=True,
      debug=True,
      open_in_browser=True,
      delay=None,
      threaded=False,
)

i get this error can any one help 

Traceback (most recent call last):
  File "C:\Users\onege\OneDrive\Desktop\pythonpro\tracker\t.py", line 1, in <module>
    from pywebcopy import save_webpage
  File "C:\Users\onege\AppData\Roaming\Python\Python310\site-packages\pywebcopy\__init__.py", line 49, in <module>
    from .configs import config, SESSION
  File "C:\Users\onege\AppData\Roaming\Python\Python310\site-packages\pywebcopy\configs.py", line 18, in <module>
    from .exceptions import AccessError
  File "C:\Users\onege\AppData\Roaming\Python\Python310\site-packages\pywebcopy\exceptions.py", line 46, in <module>
    class UrlTransformerNotSetup(PywebcopyError, UnboundLocalError):
TypeError: multiple bases have instance lay-out conflict

python version 3.10.1 
OS = Windows

**Comment by rajatomar788** [comment]
Did you read issue #90 or not?
