### ISSUE TITLE
python 3.10.4 : TypeError: multiple bases have instance lay-out conflict

### ISSUE THREAD

**Issue by anshi43** [rajatomar788/pywebcopy#97]
**This is the code** 
 
from pywebcopy import save_webpage

kwargs = {'project_name': 'site folder'}

save_webpage(
    
    # url pf the website
    url='https://www.geeksforgeeks.org/data-structures/linked-list/',
    
    # folder where the copy will be saved
    project_folder='C:\\Desktop\free',
    **kwargs
)

####################################################

**This the error occurs**

Traceback (most recent call last):
  File "C:\Users\akmv\Desktop\free\app.py", line 14, in <module>
    from pywebcopy import save_webpage
  File "C:\Users\akmv\AppData\Local\Programs\Python\Python310\lib\site-packages\pywebcopy\__init__.py", line 49, in <module>
    from .configs import config, SESSION
  File "C:\Users\akmv\AppData\Local\Programs\Python\Python310\lib\site-packages\pywebcopy\configs.py", line 18, in <module>
    from .exceptions import AccessError
  File "C:\Users\akmv\AppData\Local\Programs\Python\Python310\lib\site-packages\pywebcopy\exceptions.py", line 46, in <module>
    class UrlTransformerNotSetup(PywebcopyError, UnboundLocalError):
TypeError: multiple bases have instance lay-out conflict

How can I solve this error?

Thank you very much in advance!

**Comment by rajatomar788** [comment]
Did you read issue #90 or not?

**Comment by anshi43** [comment]
I did.

**Comment by anshi43** [comment]
Could you please tell the solution? 
TIA

**Comment by rajatomar788** [comment]
This is a python 3.10 problem, so it can only be fixed by rewriting the portions of the code.

**Comment by anshi43** [comment]
what should i change in code ? Could you please tell ?
TIA

**Comment by rajatomar788** [comment]
You have to change the inheritance of error classes from multiple bases to just a single base class as the error says.

**Comment by anshi43** [comment]
???

**Comment by rajatomar788** [comment]
Just download python version below  3.9 and done.

**Comment by Frutto-Hub** [comment]
> Just download python version below 3.9 and done.

Does it works on 3.8? On pypi it shows 3.7 is the latest it can work with.

**Comment by rajatomar788** [comment]
@Frutto-Hub yes it works on 3.7 & 3.8
